# Generated by Django 6.0.1 on 2026-04-05 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='delivery',
            options={'ordering': ['-id']},
        ),
        migrations.RemoveField(
            model_name='delivery',
            name='customer_phone',
        ),
        migrations.RemoveField(
            model_name='delivery',
            name='tailor_phone',
        ),
        migrations.AddField(
            model_name='delivery',
            name='admin_notes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='driverprofile',
            name='account_number',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='driverprofile',
            name='account_title',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='driverprofile',
            name='bank_name',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='driverprofile',
            name='iban',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='driverprofile',
            name='license_number',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='driverprofile',
            name='national_id',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='order',
            name='customer_phone',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='order',
            name='delivery_fee',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='order',
            name='payment_method',
            field=models.CharField(choices=[('card', 'Card'), ('cash', 'Cash'), ('bank_transfer', 'Bank Transfer'), ('wallet', 'Wallet')], default='card', max_length=30),
        ),
        migrations.AddField(
            model_name='order',
            name='payment_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('paid', 'Paid'), ('failed', 'Failed'), ('refunded', 'Refunded')], default='pending', max_length=30),
        ),
        migrations.AddField(
            model_name='order',
            name='subtotal',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='tailorprofile',
            name='account_number',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='tailorprofile',
            name='account_title',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='tailorprofile',
            name='bank_name',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='tailorprofile',
            name='iban',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='tailorprofile',
            name='national_id',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='tailorprofile',
            name='shop_name',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='delivery',
            name='status',
            field=models.CharField(choices=[('Pending Assignment', 'Pending Assignment'), ('Assigned', 'Assigned'), ('Picked Up', 'Picked Up'), ('In Transit', 'In Transit'), ('Delivered', 'Delivered')], default='Pending Assignment', max_length=30),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('Placed', 'Placed'), ('Confirmed', 'Confirmed'), ('In Stitching', 'In Stitching'), ('Ready', 'Ready'), ('Out for Delivery', 'Out for Delivery'), ('Delivered', 'Delivered'), ('Cancelled', 'Cancelled')], default='Placed', max_length=30),
        ),
        migrations.AlterField(
            model_name='tailorprofile',
            name='eta',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='tailorprofile',
            name='location',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='tailorprofile',
            name='rating',
            field=models.DecimalField(decimal_places=1, default=0, max_digits=3),
        ),
        migrations.AlterField(
            model_name='tailorprofile',
            name='specialty',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
