# Generated by Django 6.0.1 on 2026-04-05 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_delivery_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tailorprofile',
            name='image',
            field=models.TextField(blank=True),
        ),
    ]
