# Generated by Django 6.0.1 on 2026-04-05 13:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_tailorprofile_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='design',
            name='images',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='design',
            name='uploaded_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploaded_designs', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='design',
            name='image',
            field=models.TextField(blank=True),
        ),
    ]
