# Generated by Django 6.0.1 on 2026-04-05 13:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_design_images_design_uploaded_by_alter_design_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='fabric',
            name='uploaded_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploaded_fabrics', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='fabric',
            name='image',
            field=models.TextField(blank=True),
        ),
    ]
