# Generated by Django 6.0.1 on 2026-04-07 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_fabric_uploaded_by_alter_fabric_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('Placed', 'Placed'), ('Received', 'Received'), ('Confirmed', 'Confirmed'), ('Accepted', 'Accepted'), ('Rejected', 'Rejected'), ('In Stitching', 'In Stitching'), ('Ready', 'Ready'), ('Out for Delivery', 'Out for Delivery'), ('Delivered', 'Delivered'), ('Cancelled', 'Cancelled')], default='Received', max_length=30),
        ),
    ]
