# Generated by Django 6.0.1 on 2026-05-08 18:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_performance_indexes'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('login_time', models.DateTimeField(auto_now_add=True)),
                ('logout_time', models.DateTimeField(blank=True, null=True)),
                ('ip_address', models.CharField(blank=True, max_length=50)),
                ('user_agent', models.TextField(blank=True)),
            ],
            options={
                'ordering': ['-login_time'],
            },
        ),
        migrations.RenameIndex(
            model_name='delivery',
            new_name='core_delive_driver__828b4c_idx',
            old_name='core_delive_driver__5d95cf_idx',
        ),
        migrations.RenameIndex(
            model_name='design',
            new_name='core_design_is_acti_d0a0c0_idx',
            old_name='core_design_is_acti_4bc757_idx',
        ),
        migrations.RenameIndex(
            model_name='design',
            new_name='core_design_uploade_cf4fa8_idx',
            old_name='core_design_uploade_1fe40d_idx',
        ),
        migrations.RenameIndex(
            model_name='driverprofile',
            new_name='core_driver_is_avai_69c9ba_idx',
            old_name='core_driver_is_avai_4409ff_idx',
        ),
        migrations.RenameIndex(
            model_name='fabric',
            new_name='core_fabric_is_acti_4af4fe_idx',
            old_name='core_fabric_is_acti_949bb6_idx',
        ),
        migrations.RenameIndex(
            model_name='fabric',
            new_name='core_fabric_uploade_ace87d_idx',
            old_name='core_fabric_uploade_8a4ff1_idx',
        ),
        migrations.RenameIndex(
            model_name='measurementprofile',
            new_name='core_measur_custome_a97440_idx',
            old_name='core_measur_customer_6c5489_idx',
        ),
        migrations.RenameIndex(
            model_name='order',
            new_name='core_order_custome_fdf03b_idx',
            old_name='core_order_customer_444fd0_idx',
        ),
        migrations.RenameIndex(
            model_name='order',
            new_name='core_order_tailor__9efd93_idx',
            old_name='core_order_tailor_9be1c2_idx',
        ),
        migrations.RenameIndex(
            model_name='order',
            new_name='core_order_tailor__a48d62_idx',
            old_name='core_order_tailor_827772_idx',
        ),
        migrations.RenameIndex(
            model_name='order',
            new_name='core_order_custome_38b790_idx',
            old_name='core_order_customer_8118c0_idx',
        ),
        migrations.RenameIndex(
            model_name='tailorprofile',
            new_name='core_tailor_is_acti_b83b92_idx',
            old_name='core_tailor_is_acti_113877_idx',
        ),
        migrations.AddField(
            model_name='usersession',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='usersession',
            index=models.Index(fields=['user', '-login_time'], name='core_userse_user_id_1b94bf_idx'),
        ),
        migrations.AddIndex(
            model_name='usersession',
            index=models.Index(fields=['-login_time'], name='core_userse_login_t_8b3493_idx'),
        ),
    ]
