from django.urls import include, path
from rest_framework.routers import DefaultRouter

from .views import (
    AdminAssignDriverView,
    AdminDriverViewSet,
    AdminDesignViewSet,
    AdminFabricViewSet,
    AdminOrderDetailUpdateView,
    AdminOrderListView,
    AdminOverviewView,
    AdminTailorViewSet,
    CustomerDashboardView,
    DesignListView,
    DesignDetailView,
    DriverDeliveryDetailUpdateView,
    DriverDeliveryListView,
    DriverMeView,
    FabricListView,
    InvoiceDetailView,
    InvoiceListView,
    LoginView,
    MeasurementDetailView,
    MeasurementListCreateView,
    NotificationListView,
    OrderDetailView,
    OrderListCreateView,
    ProfileView,
    SignupView,
    TailorDetailView,
    TailorShopCatalogView,
    TailorFabricListCreateView,
    TailorDesignListCreateView,
    TailorDesignDetailView,
    TailorMeView,
    TailorOrderDetailUpdateView,
    TailorFabricDetailView,
    TailorListView,
    TailorOrderListView,
    logout_view,
)

router = DefaultRouter()
router.register('admin/tailors', AdminTailorViewSet, basename='admin-tailors')
router.register('admin/drivers', AdminDriverViewSet, basename='admin-drivers')
router.register('admin/fabrics', AdminFabricViewSet, basename='admin-fabrics')
router.register('admin/designs', AdminDesignViewSet, basename='admin-designs')

urlpatterns = [
    path('auth/signup/', SignupView.as_view(), name='signup'),
    path('auth/login/', LoginView.as_view(), name='login'),
    path('auth/logout/', logout_view, name='logout'),
    path('auth/profile/', ProfileView.as_view(), name='profile'),
    path('dashboard/customer/', CustomerDashboardView.as_view(), name='customer-dashboard'),
    path('tailors/', TailorListView.as_view(), name='tailors'),
    path('tailors/<int:pk>/', TailorDetailView.as_view(), name='tailor-detail'),
    path('tailors/<int:pk>/catalog/', TailorShopCatalogView.as_view(), name='tailor-shop-catalog'),
    path('tailor/me/', TailorMeView.as_view(), name='tailor-me'),
    path('tailor/fabrics/', TailorFabricListCreateView.as_view(), name='tailor-fabrics'),
    path('tailor/fabrics/<int:pk>/', TailorFabricDetailView.as_view(), name='tailor-fabric-detail'),
    path('tailor/designs/', TailorDesignListCreateView.as_view(), name='tailor-designs'),
    path('tailor/designs/<int:pk>/', TailorDesignDetailView.as_view(), name='tailor-design-detail'),
    path('fabrics/', FabricListView.as_view(), name='fabrics'),
    path('designs/', DesignListView.as_view(), name='designs'),
    path('designs/<int:pk>/', DesignDetailView.as_view(), name='design-detail'),
    path('measurements/', MeasurementListCreateView.as_view(), name='measurements'),
    path('measurements/<int:pk>/', MeasurementDetailView.as_view(), name='measurement-detail'),
    path('orders/', OrderListCreateView.as_view(), name='orders'),
    path('orders/<int:pk>/', OrderDetailView.as_view(), name='order-detail'),
    path('notifications/', NotificationListView.as_view(), name='notifications'),
    path('invoices/', InvoiceListView.as_view(), name='invoices'),
    path('invoices/<str:invoice_id>/', InvoiceDetailView.as_view(), name='invoice-detail'),
    path('tailor/orders/', TailorOrderListView.as_view(), name='tailor-orders'),
    path('tailor/orders/<int:pk>/', TailorOrderDetailUpdateView.as_view(), name='tailor-order-detail'),
    path('driver/me/', DriverMeView.as_view(), name='driver-me'),
    path('driver/deliveries/', DriverDeliveryListView.as_view(), name='driver-deliveries'),
    path('driver/deliveries/<int:pk>/', DriverDeliveryDetailUpdateView.as_view(), name='driver-delivery-detail'),
    path('admin/overview/', AdminOverviewView.as_view(), name='admin-overview'),
    path('admin/orders/', AdminOrderListView.as_view(), name='admin-orders'),
    path('admin/orders/<int:pk>/', AdminOrderDetailUpdateView.as_view(), name='admin-order-detail'),
    path('admin/orders/<int:order_id>/assign-driver/', AdminAssignDriverView.as_view(), name='admin-assign-driver'),
    path('', include(router.urls)),
]
